name: Prepare Local Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t testdevopsapp .

      - name: Save image for local use
        run: docker save testdevopsapp -o testdevopsapp.tar

      - name: Archive entire project (including hidden files)
        run: tar -cvf full-project.tar . --exclude=full-project.tar

      - name: Upload full project archive
        uses: actions/upload-artifact@v4
        with:
          name: full-project-archive
          path: full-project.tar
